version: '3.4'

services:
  webapi:
    image: webapi
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Winter_Silence"
      ACCEPT_EULA: "Y"